project 'GJRxSwift.xcodeproj'
platform :ios, '9.0'
use_frameworks!

target 'GJRxSwift' do

    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources', '~> 3.0'
    pod 'Alamofire', '~> 4.7'
    pod 'RxAlamofire'
    pod 'ObjectMapper', '~> 3.3'
    pod 'Moya'

end
